# *LINEAR ALGEBRA*

## Rank

> The **rank** of a matrix - the dimension of the vector space generated (or spanned) by its columns, maximal number of **linearly independent** columns of the matrix.


Numpy Linear algebra


> The **rank** of an array - the number of signular values of the array.






The rank is commonly denoted by:

$rank(A)$

$rk(A)$

In [2]:
from numpy.linalg import matrix_rank
import numpy as np

In [5]:
matrix_A = np.array([[1, 2], [3, 4]])
matrix_B = np.array([[1, 0], [0, 0]])

In [6]:
matrix_A_transpose = np.transpose(matrix_A)
matrix_B_transpose = np.transpose(matrix_B)

In [7]:
matrix_A_rank = matrix_rank(matrix_A)
matrix_B_rank = matrix_rank(matrix_B)

In [15]:
rank_description = 'Matrix \n {0} \n rank (rząd macierzy): {1}'

In [16]:
print(rank_description.format(matrix_A, matrix_A_rank))
print(rank_description.format(matrix_B, matrix_B_rank))

Matrix 
 [[1 2]
 [3 4]] 
 rank (rząd macierzy): 2
Matrix 
 [[1 0]
 [0 0]] 
 rank (rząd macierzy): 1


$rank(A) = rank(A^{T})$

In [9]:
rank_check = matrix_A_rank == matrix_rank(matrix_A_transpose) and matrix_B_rank == matrix_rank(matrix_B_transpose)

In [10]:
print('Matrix rank is equal to the same matrix rank but transposed:', rank_check)

Matrix rank is equal to the same matrix rank but transposed: True


In [24]:
print(rank_description.format(np.zeros((4,)), matrix_rank(np.zeros((4,)))))

Matrix 
 [0. 0. 0. 0.] 
 rank (rząd macierzy): 0


In [25]:
print(rank_description.format(np.ones((4,)), matrix_rank(np.ones((4,)))))

Matrix 
 [1. 1. 1. 1.] 
 rank (rząd macierzy): 1


In [27]:
print(rank_description.format(np.zeros((1,4)), matrix_rank(np.zeros((1,4)))))

Matrix 
 [[0. 0. 0. 0.]] 
 rank (rząd macierzy): 0


In [28]:
print(rank_description.format(np.ones((1,4)), matrix_rank(np.ones((1,4)))))

Matrix 
 [[1. 1. 1. 1.]] 
 rank (rząd macierzy): 1


In [29]:
print(rank_description.format(np.zeros((4,4)), matrix_rank(np.zeros((4,4)))))

Matrix 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 
 rank (rząd macierzy): 0


In [30]:
print(rank_description.format(np.ones((4,4)), matrix_rank(np.ones((4,4)))))

Matrix 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] 
 rank (rząd macierzy): 1




---


## Norm

The norm is generally used to evaluate the error of the model.



*   L1 norm - the sum of the absolute values of the vector
*   L2 norm - the square root of the sum of the squared vector values
*   Max norm - the maximum vector values


Properties:

*   $ ||x|| \geq 0 $

*   $ ||X||  = 0 \iff x = 0 $

*   $ ||x + y|| \leq ||x|| + ||y|| $

*   $ ||λx|| = |λ|||x|| $







In [31]:
from numpy.linalg import norm

In [34]:
norm_description = 'Vector \n {0} \n norm ({1}) value: {2}'

In [43]:
x = np.array([1, 2, 3])

In [44]:
print(norm_description.format(x, 'L1', norm(x, 1)))

Vector 
 [1 2 3] 
 norm (L1) value: 6.0


In [45]:
print(norm_description.format(x, 'L2', norm(x)))

Vector 
 [1 2 3] 
 norm (L2) value: 3.7416573867739413


In [46]:
print(norm_description.format(x, 'inf', norm(x, np.inf)))

Vector 
 [1 2 3] 
 norm (inf) value: 3.0
