# *LINEAR ALGEBRA*

***
## Rank

> The **rank** of a matrix - the dimension of the vector space generated (or spanned) by its columns, maximal number of **linearly independent** columns of the matrix.


Numpy Linear algebra


> The **rank** of an array - the number of signular values of the array.






The rank is commonly denoted by:

$rank(A)$

$rk(A)$

In [2]:
from numpy.linalg import matrix_rank
import numpy as np

In [3]:
matrix_A = np.array([[1, 2], [3, 4]])
matrix_B = np.array([[1, 0], [0, 0]])

In [4]:
matrix_A_transpose = np.transpose(matrix_A)
matrix_B_transpose = np.transpose(matrix_B)

In [5]:
matrix_A_rank = matrix_rank(matrix_A)
matrix_B_rank = matrix_rank(matrix_B)

In [6]:
rank_description = 'Matrix \n {0} \n rank (rząd macierzy): {1}'

In [7]:
print(rank_description.format(matrix_A, matrix_A_rank))
print(rank_description.format(matrix_B, matrix_B_rank))

Matrix 
 [[1 2]
 [3 4]] 
 rank (rząd macierzy): 2
Matrix 
 [[1 0]
 [0 0]] 
 rank (rząd macierzy): 1


$rank(A) = rank(A^{T})$

In [8]:
rank_check = matrix_A_rank == matrix_rank(matrix_A_transpose) and matrix_B_rank == matrix_rank(matrix_B_transpose)

In [9]:
print('Matrix rank is equal to the same matrix rank but transposed:', rank_check)

Matrix rank is equal to the same matrix rank but transposed: True


In [10]:
print(rank_description.format(np.zeros((4,)), matrix_rank(np.zeros((4,)))))

Matrix 
 [0. 0. 0. 0.] 
 rank (rząd macierzy): 0


In [11]:
print(rank_description.format(np.ones((4,)), matrix_rank(np.ones((4,)))))

Matrix 
 [1. 1. 1. 1.] 
 rank (rząd macierzy): 1


In [12]:
print(rank_description.format(np.zeros((1,4)), matrix_rank(np.zeros((1,4)))))

Matrix 
 [[0. 0. 0. 0.]] 
 rank (rząd macierzy): 0


In [13]:
print(rank_description.format(np.ones((1,4)), matrix_rank(np.ones((1,4)))))

Matrix 
 [[1. 1. 1. 1.]] 
 rank (rząd macierzy): 1


In [14]:
print(rank_description.format(np.zeros((4,4)), matrix_rank(np.zeros((4,4)))))

Matrix 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 
 rank (rząd macierzy): 0


In [15]:
print(rank_description.format(np.ones((4,4)), matrix_rank(np.ones((4,4)))))

Matrix 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] 
 rank (rząd macierzy): 1


****
## Symmetric matrix

$A^{T} = A$

In [16]:
A = np.array([[1, 1, -1], [1, 2, 0], [-1, 0, 5]])
A

array([[ 1,  1, -1],
       [ 1,  2,  0],
       [-1,  0,  5]])

In [17]:
A_t = A.transpose()
A_t

array([[ 1,  1, -1],
       [ 1,  2,  0],
       [-1,  0,  5]])

In [18]:
np.array_equal(A, A_t)

True



---


## Norm

The norm is generally used to evaluate the error of the model.



*   L1 norm - the sum of the absolute values of the vector (the Manhattan/Taxicab Distance, the Mean Absolute Error (MAE), the Least Absolute Shrinkage and Selection Operator (LASSO))
*   L2 norm - the square root of the sum of the squared vector values (the Euclidean Distance, the Mean Squared Error (MSE) / Least Squares Error, or the Ridge Operator)
*   Max norm - the maximum vector values


Properties:

*   $ ||x|| \geq 0 $

*   $ ||x||  = 0 \iff x = 0 $

*   $ ||x + y|| \leq ||x|| + ||y|| $

*   $ ||λx|| = |λ|||x|| $







In [19]:
from numpy.linalg import norm

In [20]:
norm_description = 'Vector \n {0} \n norm ({1}) value: {2}'

In [21]:
x = np.array([1, 2, 3])

In [22]:
print(norm_description.format(x, 'L1', norm(x, 1)))

Vector 
 [1 2 3] 
 norm (L1) value: 6.0


In [23]:
norm_1_value = 0

for value in x:
  norm_1_value += abs(value)

print(norm_description.format(x, 'L1', norm_1_value))

Vector 
 [1 2 3] 
 norm (L1) value: 6


In [24]:
print(norm_description.format(x, 'L2', norm(x)))

Vector 
 [1 2 3] 
 norm (L2) value: 3.7416573867739413


In [25]:
norm_2_value = 0

for value in x:
  norm_2_value  += value**2

norm_2_value = np.sqrt(norm_2_value)

print(norm_description.format(x, 'L2', norm_2_value))

Vector 
 [1 2 3] 
 norm (L2) value: 3.7416573867739413


In [26]:
print(norm_description.format(x, 'inf', norm(x, np.inf)))

Vector 
 [1 2 3] 
 norm (inf) value: 3.0


In [27]:
norm_inf_value = 0

for value in x:
  if abs(value) > norm_inf_value:
    norm_inf_value = value

print(norm_description.format(x, 'inf', norm_inf_value))

Vector 
 [1 2 3] 
 norm (inf) value: 3


****
## Dot product

> $ <x, y> $

Pairs of $ (V<x, y>) $ is an Eucleadian space.

The dot product of two functions (u, v):

$ <u, v> = \int_{a}^{b} u(x)v(x) \,dx \ $

The dot product in $ R^{n} $:

$x^{T}y = \sum_{i=1}^{n} x_i y_i $

In [28]:
v1 = np.array([-2, 1])
v2 = np.array([0, 3])

In [29]:
np.dot(v1, v2)

3

The Euclidean length of the vector

$ ||x|| = 	\sqrt{<x, x>}$

$ <x, y> = x^{T}y $

If the vectors x are orthogonal (i.e., their angle is π / 2 or 90°).
$ <x, y> = 0 $

****
## Orthogonal matrix

> real square matrix whose columns and rows are orthonormal vectors

$ AA^{T} = I = A^{T}A $

$ A^{-1} = A^{T} $

In [30]:
A = np.array([[-1, 0], [0, 1]])
A_t = np.transpose(A)
A_inv = np.linalg.inv(A)

In [31]:
A

array([[-1,  0],
       [ 0,  1]])

In [32]:
A_t

array([[-1,  0],
       [ 0,  1]])

In [33]:
A_inv

array([[-1., -0.],
       [ 0.,  1.]])

In [34]:
res = np.dot(A, A_t)
res

array([[1, 0],
       [0, 1]])

In [35]:
I = np.eye(2)
I

array([[1., 0.],
       [0., 1.]])

In [36]:
np.all(np.equal(res, I))

True

In [37]:
np.all(np.equal(A_inv, A_t))

True

***

## Determinant

If 

$ det(A) \neq 0 $ 

then inverse matrix

$  A^{-1} $

exists.

A square matrix has the

$ det(A) \neq 0 $

if and only if

$ rk(A) = n $

In [38]:
A = np.array([[1, 2], [3, 4]])
A

array([[1, 2],
       [3, 4]])

In [39]:
det = np.linalg.det(A)
det

-2.0000000000000004

In [40]:
det = A[0][0] * A[1][1] - A[0][1] * A[1][0]
det

-2

In [41]:
np.linalg.matrix_rank(A)

2

In [42]:
A_t_l = np.array([
    [3, 0, 0],
    [1, 1, 0],
    [4, 3, 2],
])

In [43]:
np.linalg.det(A_t_l)

5.999999999999998

In [44]:
A_t_h = np.array([
    [3, 5, 6],
    [0, 10, 7],
    [0, 0, 2],
])

In [45]:
np.linalg.det(A_t_h)

60.000000000000036

***
## Eigenvectors and eigenvalues
#### Wektory i wartości własne

$ Ax = \lambda x $

$ A - square matrix $

$ x - eigenvector $

$ \lambda - eigenvalue $

The set of all eigenvalues $ \lambda $ of $ A $ - spectrum $ A $.

The matrix $ A $ and $ A^{T} $ have the same eigenvalues $ \lambda $ but not necessarily the same eigenvectors $ x $.

The determinant of matrix $ A $ with eigenvalues $ \lambda_i $ is equal to:

$ det(A) = \prod_{i=1}^n \lambda_i $

In [47]:
B = np.array([
    [1, 2],
    [3, 4]
])

In [51]:
w, v = np.linalg.eig(B)

In [52]:
w

array([-0.37228132,  5.37228132])

In [53]:
v

array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]])

***
## Trace

$ tr(A) = \sum_{i=1}^n a_ii $

$ tr(A) = \sum_{i=1}^n \lambda_i $

In [56]:
C = np.array([
    [-1, 2],
    [3, 0]
])

In [57]:
np.trace(C)

-1