# *LINEAR ALGEBRA*

## Rank

> The **rank** of a matrix - the dimension of the vector space generated (or spanned) by its columns, maximal number of **linearly independent** columns of the matrix.


Numpy Linear algebra


> The **rank** of an array - the number of signular values of the array.






The rank is commonly denoted by:

$rank(A)$

$rk(A)$

In [2]:
from numpy.linalg import matrix_rank
import numpy as np

In [3]:
matrix_A = np.array([[1, 2], [3, 4]])
matrix_B = np.array([[1, 0], [0, 0]])

In [4]:
matrix_A_transpose = np.transpose(matrix_A)
matrix_B_transpose = np.transpose(matrix_B)

In [5]:
matrix_A_rank = matrix_rank(matrix_A)
matrix_B_rank = matrix_rank(matrix_B)

In [6]:
rank_description = 'Matrix \n {0} \n rank (rząd macierzy): {1}'

In [7]:
print(rank_description.format(matrix_A, matrix_A_rank))
print(rank_description.format(matrix_B, matrix_B_rank))

Matrix 
 [[1 2]
 [3 4]] 
 rank (rząd macierzy): 2
Matrix 
 [[1 0]
 [0 0]] 
 rank (rząd macierzy): 1


$rank(A) = rank(A^{T})$

In [8]:
rank_check = matrix_A_rank == matrix_rank(matrix_A_transpose) and matrix_B_rank == matrix_rank(matrix_B_transpose)

In [9]:
print('Matrix rank is equal to the same matrix rank but transposed:', rank_check)

Matrix rank is equal to the same matrix rank but transposed: True


In [10]:
print(rank_description.format(np.zeros((4,)), matrix_rank(np.zeros((4,)))))

Matrix 
 [0. 0. 0. 0.] 
 rank (rząd macierzy): 0


In [11]:
print(rank_description.format(np.ones((4,)), matrix_rank(np.ones((4,)))))

Matrix 
 [1. 1. 1. 1.] 
 rank (rząd macierzy): 1


In [12]:
print(rank_description.format(np.zeros((1,4)), matrix_rank(np.zeros((1,4)))))

Matrix 
 [[0. 0. 0. 0.]] 
 rank (rząd macierzy): 0


In [13]:
print(rank_description.format(np.ones((1,4)), matrix_rank(np.ones((1,4)))))

Matrix 
 [[1. 1. 1. 1.]] 
 rank (rząd macierzy): 1


In [14]:
print(rank_description.format(np.zeros((4,4)), matrix_rank(np.zeros((4,4)))))

Matrix 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 
 rank (rząd macierzy): 0


In [15]:
print(rank_description.format(np.ones((4,4)), matrix_rank(np.ones((4,4)))))

Matrix 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] 
 rank (rząd macierzy): 1


## Symmetric matrix

$A^{T} = A$

In [45]:
A = np.array([[1, 1, -1], [1, 2, 0], [-1, 0, 5]])
A

array([[ 1,  1, -1],
       [ 1,  2,  0],
       [-1,  0,  5]])

In [46]:
A_t = A.transpose()
A_t

array([[ 1,  1, -1],
       [ 1,  2,  0],
       [-1,  0,  5]])

In [47]:
np.array_equal(A, A_t)

True



---


## Norm

The norm is generally used to evaluate the error of the model.



*   L1 norm - the sum of the absolute values of the vector (the Manhattan/Taxicab Distance, the Mean Absolute Error (MAE), the Least Absolute Shrinkage and Selection Operator (LASSO))
*   L2 norm - the square root of the sum of the squared vector values (the Euclidean Distance, the Mean Squared Error (MSE) / Least Squares Error, or the Ridge Operator)
*   Max norm - the maximum vector values


Properties:

*   $ ||x|| \geq 0 $

*   $ ||x||  = 0 \iff x = 0 $

*   $ ||x + y|| \leq ||x|| + ||y|| $

*   $ ||λx|| = |λ|||x|| $







In [16]:
from numpy.linalg import norm

In [17]:
norm_description = 'Vector \n {0} \n norm ({1}) value: {2}'

In [23]:
x = np.array([1, 2, 3])

In [24]:
print(norm_description.format(x, 'L1', norm(x, 1)))

Vector 
 [1 2 3] 
 norm (L1) value: 6.0


In [30]:
norm_1_value = 0

for value in x:
  norm_1_value += abs(value)

print(norm_description.format(x, 'L1', norm_1_value))

Vector 
 [1 2 3] 
 norm (L1) value: 6


In [20]:
print(norm_description.format(x, 'L2', norm(x)))

Vector 
 [1 2 3] 
 norm (L2) value: 3.7416573867739413


In [34]:
norm_2_value = 0

for value in x:
  norm_2_value  += value**2

norm_2_value = np.sqrt(norm_2_value)

print(norm_description.format(x, 'L2', norm_2_value))

Vector 
 [1 2 3] 
 norm (L2) value: 3.7416573867739413


In [35]:
print(norm_description.format(x, 'inf', norm(x, np.inf)))

Vector 
 [1 2 3] 
 norm (inf) value: 3.0


In [38]:
norm_inf_value = 0

for value in x:
  if abs(value) > norm_inf_value:
    norm_inf_value = value

print(norm_description.format(x, 'inf', norm_inf_value))

Vector 
 [1 2 3] 
 norm (inf) value: 3


## Dot product

> $ <x, y> $

Pairs of $ (V<x, y>) $ is an Eucleadian space.

The dot product of two functions (u, v):

$ <u, v> = \int_{a}^{b} u(x)v(x) \,dx \ $

The dot product in $ R^{n} $:

$x^{T}y = \sum_{i=1}^{n} x_i y_i $

In [42]:
v1 = np.array([-2, 1])
v2 = np.array([0, 3])

In [43]:
np.dot(v1, v2)

3

The Euclidean length of the vector

$ ||x|| = 	\sqrt{<x, x>}$

$ <x, y> = x^{T}y $

If the vectors x are orthogonal (i.e., their angle is π / 2 or 90°).
$ <x, y> = 0 $

## Orthogonal matrix

> real square matrix whose columns and rows are orthonormal vectors

$ AA^{T} = I = A^{T}A $

$ A^{-1} = A^{T} $

In [55]:
A = np.array([[-1, 0], [0, 1]])
A_t = np.transpose(A)
A_inv = np.linalg.inv(A)

In [56]:
A

array([[-1,  0],
       [ 0,  1]])

In [57]:
A_t

array([[-1,  0],
       [ 0,  1]])

In [58]:
A_inv

array([[-1., -0.],
       [ 0.,  1.]])

In [53]:
res = np.dot(A, A_t)
res

array([[1, 0],
       [0, 1]])

In [52]:
I = np.eye(2)
I

array([[1., 0.],
       [0., 1.]])

In [54]:
np.all(np.equal(res, I))

True

In [59]:
np.all(np.equal(A_inv, A_t))

True